# Generated by Django 5.1.2 on 2025-05-06 16:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='Сondition_st',
        ),
        migrations.AddField(
            model_name='ad',
            name='Сondition',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Condition',
        ),
    ]
