# Generated by Django 5.1.2 on 2025-05-10 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_remove_ad_сondition_st_ad_сondition_delete_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('сreated_at', models.DateField(default=None)),
                ('ad_receiver_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.ad')),
                ('ad_sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='ads.ad')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ads.status')),
            ],
        ),
    ]
